config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: %i[sessions passwords]
  devise_for :users
  root to: 'events#index'
  resources :events
  namespace :admin do
    root to: 'events#index'
    resources :events, except: %i[new create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user = nil)
    can :manage, :all
    cannot(%i[update destroy], Event) { |event| event.user != user }
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability

  def initialize(_user = nil)
    can :manage, :all
    cannot :create, Event
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :starttime, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def current_ability
    AdminAbility.new(current_admin)
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  load_and_authorize_resource
  before_action :set_event, only: %i[edit update destroy]

  def index
    @events = Event.all.page(params[:page]).per(10)
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to admin_event_path(@event), notice: t('views.events.update.success')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to admin_events_path, notice: t('views.events.destroy.success')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :location, :starttime, :endtime, :organizeremail, :organizertelegram, :link)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  load_and_authorize_resource
  before_action :set_event, only: %i[edit update destroy]

  def index
    @events = Event.all.page(params[:page]).per(10)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.events.new
  end

  def edit; end

  def create
    @event = current_user.events.new(event_params)

    if @event.save
      redirect_to @event, notice: t('views.events.create.success')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: t('views.events.update.success')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: t('views.events.destroy.success')
  end

  private

  def set_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :location, :starttime, :endtime, :organizeremail, :organizertelegram, :link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    = link_to 'Events', root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        - if current_admin
          %li.nav-item
            = link_to t('views.admin.events.index.title'), admin_events_path, class: 'nav-link'
          %li.nav-item
            = current_admin.email
          %li.nav-item
            = link_to t('common.sign_out'), destroy_admin_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            = link_to t('common.sign_in'), new_admin_session_path, class: 'nav-link'

app/views/admin/events/_form.html.haml
= simple_form_for @event, url: [:admin, @event] do |f|
  - if @event.errors.any?
    #error_explanation
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.input :title
  .field
    = f.input :description
  .field
    = f.input :location
  .field
    = f.input :starttime
  .field
    = f.input :endtime
  .field
    = f.input :organizeremail
  .field
    = f.input :organizertelegram
  .field
    = f.input :link
  .actions
    = f.submit t('common.save')

app/views/admin/events/edit.html.haml
%h1= t('views.admin.events.edit.title')

= render 'form'

= link_to t('common.show'), edit_admin_event_path(@event)
\|
= link_to t('common.back'), admin_events_path

app/views/admin/events/index.html.haml
%h1= t('views.admin.events.index.title')

%table
  %thead
    %tr
      %th= Event.human_attribute_name(:title)
      %th= Event.human_attribute_name(:description)
      %th= Event.human_attribute_name(:location)
      %th= Event.human_attribute_name(:starttime)
      %th= Event.human_attribute_name(:endtime)
      %th= Event.human_attribute_name(:organizeremail)
      %th= Event.human_attribute_name(:organizertelegram)
      %th= Event.human_attribute_name(:link)
      %th
      %th
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= event.title
        %td= event.description
        %td= event.location
        %td= event.starttime
        %td= event.endtime
        %td= event.organizeremail
        %td= event.organizertelegram
        %td= event.link
        %td= link_to t('common.show'), event
        %td= link_to t('common.edit'), edit_admin_event_path(event)
        %td= link_to t('common.destroy'), admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' }

%br

= paginate @events

app/views/admin/events/new.html.haml
%h1= t('views.admin.events.new.title')

= render 'form'

= link_to t('common.back'), admin_events_path

app/views/admin/events/show.html.haml
%h2
  = Event.model_name.human
  = @event.title

%p
  = @event.description
%p
  = @event.location
%p
  = @event.starttime
%p
  = @event.endtime
%p
  = @event.organizeremail
%p
  = @event.organizertelegram
%p
  = @event.link

= link_to t('common.edit'), edit_admin_event_path(@event)
\|
= link_to t('common.back'), admin_events_path

app/views/application/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    = link_to 'Events', root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        - if current_user
          %li.nav-item
            = link_to t('common.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            = link_to t('common.sign_in'), new_user_session_path, class: 'nav-link'
          %li.nav-item
            = link_to t('common.sign_up'), new_user_registration_path, class: 'nav-link'

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.input :title
  .field
    = f.input :description
  .field
    = f.input :location
  .field
    = f.input :starttime
  .field
    = f.input :endtime
  .field
    = f.input :organizeremail
  .field
    = f.input :organizertelegram
  .field
    = f.input :link
  .actions
    = f.submit t('common.save')

app/views/events/edit.html.haml
%h1= t('views.events.edit.title')

= render 'form'

= link_to t('common.show'), @event
\|
= link_to t('common.back'), events_path

app/views/events/index.html.haml
%h1= t('views.events.index.title')

%table
  %thead
    %tr
      %th= Event.human_attribute_name(:title)
      %th= Event.human_attribute_name(:description)
      %th= Event.human_attribute_name(:location)
      %th= Event.human_attribute_name(:starttime)
      %th= Event.human_attribute_name(:endtime)
      %th= Event.human_attribute_name(:organizeremail)
      %th= Event.human_attribute_name(:organizertelegram)
      %th= Event.human_attribute_name(:link)
      %th
      %th
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= event.title
        %td= event.description
        %td= event.location
        %td= event.starttime
        %td= event.endtime
        %td= event.organizeremail
        %td= event.organizertelegram
        %td= event.link
        %td= link_to t('common.show'), event
        %td= link_to t('common.edit'), edit_event_path(event)
        %td= link_to t('common.destroy'), event, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to t('views.events.index.new'), new_event_path

= paginate @events

app/views/events/new.html.haml
%h1= t('views.events.new.title')

= render 'form'

= link_to t('common.back'), events_path

app/views/events/show.html.haml
%h2
  = Event.model_name.human
  = @event.title

%p#notice= notice

%p
  = @event.description
%p
  = @event.location
%p
  = @event.starttime
%p
  = @event.endtime
%p
  = @event.organizeremail
%p
  = @event.organizertelegram
%p
  = @event.link

= link_to t('common.edit'), edit_event_path(@event)
\|
= link_to t('common.back'), events_path

app/views/layouts/_messages.html.haml
#messages
  - if alert
    #flash_alert.alert.alert-danger
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      %div=alert
  - if notice
    .alert.alert-success
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      %div=notice

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CustomRor
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'admin/navigation'
    = render 'layouts/messages'
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CustomRor
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'navigation'
    = render 'messages'
    = yield